### ISSUE TITLE
Make a text-only fallback for slack notifcation

### ISSUE THREAD

**Issue by epaulet** [rainforestapp/rainforest-integrations#35]
Right now the fallback is the same as the default message for some reason.

**Comment by epaulet** [comment]
Fallback text is defined here: https://api.slack.com/docs/attachments

**Comment by dgolman** [comment]
Do you want me just to change text -> fallback? According to the slack docs "text:" is optional, whereas, "fallback:" seems to be the only one needed.

**Comment by epaulet** [comment]
The text is there for clients who can read markup so we should keep both of them.
