### ISSUE TITLE
gem install rainforest-integrations

### ISSUE THREAD

**Issue by cantonic** [rainforestapp/rainforest-integrations#6]
`gem install rainforest-integrations` (like described in README) leads to `ERROR:  Could not find a valid gem 'rainforest-integrations' (>= 0) in any repository`. The gem is not on rubygems.org .

**Comment by smathieu** [comment]
This gem is not meant to be installed by any app other than Rainforest itself. May I ask what you are trying to do?

If you want to add an integration, you should be able to clone the repository and run the code locally.

**Comment by cantonic** [comment]
Oh ok. I was about to add an integration to it for [gitter.im](http://gitter.im/)
Thanks for the explanation.
